//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unidad
    {
        public int IdUnidad { get; set; }
        public string Nombre { get; set; }
        public string NombrePropietario { get; set; }
        public string ApellidoPropietario { get; set; }
        public string EmailPropietario { get; set; }
        public Nullable<int> Superficie { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual Consorcio Consorcio { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
